# Generated by Django 2.0.5 on 2018-05-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninjas', '0005_dojo_ninja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='Dojos',
            new_name='dojo',
        ),
    ]
