# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wisher',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
