# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-16 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
