# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-17 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.CharField(default='email@email.com', max_length=255),
            preserve_default=False,
        ),
    ]
